// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorVisualDNA.Server.Data;

#nullable disable

namespace HakanBoardGames.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGBoardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BoardGameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Releasd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SavedToDatabaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGCreator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.Property<int>("Min")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGCategory", b =>
                {
                    b.HasOne("HakanBoardGames.Shared.BoardGameModels.BGBoardGame", "BoardGame")
                        .WithMany("Categories")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGCreator", b =>
                {
                    b.HasOne("HakanBoardGames.Shared.BoardGameModels.BGBoardGame", "BoardGame")
                        .WithMany("Creators")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGPlayer", b =>
                {
                    b.HasOne("HakanBoardGames.Shared.BoardGameModels.BGBoardGame", "BoardGame")
                        .WithMany("Players")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("HakanBoardGames.Shared.BoardGameModels.BGBoardGame", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Creators");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
